/* =========================================================
 * Lumi Runtime  —  generated by the Lumi compiler prototype
 * Perceus reference-counting with allocation reuse
 * ========================================================= */
#ifndef LUMI_RUNTIME_H
#define LUMI_RUNTIME_H

#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdnoreturn.h>

/* ── Value representation (single source of truth) ───────
 *
 * Header (always 16 bytes):
 *   offset 0x00: uint32_t rc
 *   offset 0x04: uint32_t tag
 *   offset 0x08: uint32_t size   // payload byte length
 *   offset 0x0C: uint32_t _pad   // keeps payload 8-byte aligned
 *   offset 0x10: uint8_t payload[size]
 *
 * Tag -> payload encoding -> constructor path:
 *
 *   TAG_UNIT/TAG_TRUE/TAG_FALSE/TAG_NIL/TAG_ZERO/TAG_NONE
 *   payload: empty (size = 0)
 *   constructors: static singletons (for unit/true/false) and alloc_con/reuse_con
 *
 *   TAG_INT
 *   payload: int64_t value (size = sizeof(int64_t))
 *   constructors: lumi_int, static singletons lumi_int0/lumi_int1
 *
 *   TAG_STR
 *   payload: NUL-terminated bytes, including '\0'
 *   size: strlen(s) + 1
 *   constructors: lumi_str, static singleton lumi_empty_str
 *
 *   TAG_CLOSURE
 *   payload: [LumiFn fn][Value* capture_0]...[Value* capture_n-1]
 *   size: sizeof(LumiFn) + n * sizeof(Value*)
 *   constructors: alloc_closure_0, alloc_closure
 *
 *   Record constructor tags (product types; e.g. TAG_CONS/TAG_SOME/TAG_SUCC)
 *   payload: Value* fields[]
 *   size: nfields * sizeof(Value*)
 *   constructors: alloc_con, reuse_con
 *
 * Ownership/RC notes:
 *   - A Value owns exactly its allocation (header + payload bytes).
 *   - rc_dec dispatches by tag to decref nested Value* references where present.
 *   - Immortal values are represented by a large rc sentinel and skipped by rc_dec.
 * ─────────────────────────────────────────────────────── */
struct Value;
typedef struct Value *(*LumiFn)(struct Value *env, struct Value *arg);

typedef struct Value
{
    uint32_t rc;
    uint32_t tag;
    uint32_t size; /* payload size in bytes */
    uint32_t _pad; /* alignment: keeps payload 8-byte aligned */
    uint8_t payload[];
} Value;

/* ── Reuse token ─────────────────────────────────────────── */
typedef struct
{
    Value *mem;
} ReuseToken;

/* ── Constructor tags ────────────────────────────────────── */
enum
{
    TAG_FALSE = 0,
    TAG_TRUE = 1,
    TAG_NIL = 2,
    TAG_CONS = 3,
    TAG_NONE = 4,
    TAG_SOME = 5,
    TAG_SUCC = 6,
    TAG_ZERO = 7,
    TAG_STR = 8,
    TAG_INT = 9,
    TAG_UNIT = 10,
    TAG_CLOSURE = 0xFFFFFFFE,
};

/* ── RC primitives ───────────────────────────────────────── */

static inline void rc_inc(Value *v)
{
    if (v)
        v->rc++;
}

static inline void rc_dec(Value *v)
{
    if (!v || v->rc > 0xFFFF00)
        return; /* immortal */
    if (--v->rc == 0)
    {
        if (v->tag == TAG_CLOSURE) // decrement the captures variable values
        {
            /* Skip fn pointer; traverse captures */
            Value **caps = (Value **)(v->payload + sizeof(LumiFn));
            uint32_t ncaps = (v->size - (uint32_t)sizeof(LumiFn)) / (uint32_t)sizeof(Value *);
            for (uint32_t i = 0; i < ncaps; i++)
            {
                rc_dec(caps[i]);
            }
        }
        else if (v->tag != TAG_INT && v->tag != TAG_STR)
        {
            // Record/product constructors store payload as Value* fields[].
            uint32_t nfields = v->size / (uint32_t)sizeof(Value *);
            Value **fields = (Value **)v->payload;
            for (uint32_t i = 0; i < nfields; i++)
                rc_dec(fields[i]);
        }
        free(v);
    }
}

/* ── Reuse primitives ────────────────────────────────────────
 *
 *  try_reuse(v): if RC==1, hand the allocation to a ReuseToken.
 *                if RC>1,  decrement and return a NULL token.
 *
 *  reuse_con / alloc_con: use or ignore the token, then
 *  initialise the header (rc=1, tag, size).
 * ─────────────────────────────────────────────────────────── */

static inline ReuseToken try_reuse(Value *v)
{
    if (!v)
        return (ReuseToken){NULL};
    if (v->rc == 1)
        return (ReuseToken){v};
    rc_dec(v);
    return (ReuseToken){NULL};
}

static inline Value *reuse_con(ReuseToken tok, uint32_t tag, uint32_t nfields)
{
    uint32_t size = nfields * (uint32_t)sizeof(Value *);
    Value *v = tok.mem ? tok.mem : (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = tag;
    v->size = size;
    v->_pad = 0;
    return v;
}

static inline Value *alloc_con(uint32_t tag, uint32_t nfields)
{
    uint32_t size = nfields * (uint32_t)sizeof(Value *);
    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = tag;
    v->size = size;
    v->_pad = 0;
    return v;
}

/* ── Field accessors ─────────────────────────────────────── */

static inline Value *field(Value *v, uint32_t i)
{
    return ((Value **)v->payload)[i];
}

static inline void set_field(Value *v, uint32_t i, Value *val)
{
    ((Value **)v->payload)[i] = val;
}

static inline Value *closure_cap(Value *env, uint32_t i)
{
    return ((Value **)(env->payload + sizeof(LumiFn)))[i];
}

static inline uint32_t tag_of(Value *v) { return v ? v->tag : 0; }

/* ── Closure primitives ──────────────────────────────────────
 *
 *  alloc_closure(fn, ncaptures, cap0, cap1, ...):
 *    Allocates a closure; payload = [fn | cap0 | cap1 | ...]
 *
 *  apply(f, arg):
 *    Dispatches through the fn pointer in f's payload.
 *    Both f and arg are owned by this call.
 * ─────────────────────────────────────────────────────────── */

static inline Value *alloc_closure_0(LumiFn fn)
{
    uint32_t size = (uint32_t)sizeof(LumiFn);
    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = TAG_CLOSURE;
    v->size = size;
    v->_pad = 0;
    *(LumiFn *)v->payload = fn;
    return v;
}

#include <stdarg.h>
static Value *alloc_closure(LumiFn fn, uint32_t n, ...)
{
    // the LumiFn struct and n Value pointers
    uint32_t size = (uint32_t)sizeof(LumiFn) + n * (uint32_t)sizeof(Value *);
    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = TAG_CLOSURE;
    v->size = size;
    v->_pad = 0;
    *(LumiFn *)v->payload = fn;
    Value **caps = (Value **)(v->payload + sizeof(LumiFn));
    va_list ap;
    va_start(ap, n);
    for (uint32_t i = 0; i < n; i++)
        caps[i] = va_arg(ap, Value *);
    va_end(ap);
    return v;
}

static inline Value *apply(Value *f, Value *arg)
{
    return (*(LumiFn *)f->payload)(f, arg);
}

/* ── Primitive value constructors ────────────────────────── */

static Value LUMI_UNIT_VAL = {0xFFFFFFFF, TAG_UNIT, 0, 0};
static Value LUMI_TRUE_VAL = {0xFFFFFFFF, TAG_TRUE, 0, 0};
static Value LUMI_FALSE_VAL = {0xFFFFFFFF, TAG_FALSE, 0, 0};

typedef struct
{
    uint32_t rc;
    uint32_t tag;
    uint32_t size;
    uint32_t _pad;
    int64_t payload;
} StaticIntValue;

typedef struct
{
    uint32_t rc;
    uint32_t tag;
    uint32_t size;
    uint32_t _pad;
    char payload[1];
} StaticEmptyStrValue;

static StaticIntValue LUMI_INT0_VAL = {0xFFFFFFFF, TAG_INT, sizeof(int64_t), 0, 0};
static StaticIntValue LUMI_INT1_VAL = {0xFFFFFFFF, TAG_INT, sizeof(int64_t), 0, 1};
static StaticEmptyStrValue LUMI_EMPTY_STR_VAL = {0xFFFFFFFF, TAG_STR, 1, 0, ""};

static inline Value *lumi_unit(void) { return &LUMI_UNIT_VAL; }
static inline Value *lumi_bool(int b) { return b ? &LUMI_TRUE_VAL : &LUMI_FALSE_VAL; }
static inline int lumi_is_true(Value *v) { return v && v->tag == TAG_TRUE; }

static inline Value *lumi_global(Value *v)
{
    v->rc = 0xFFFFFFFF;
    return v;
}
static inline void lumi_release_global(Value *v)
{
    v->rc = 1;
    rc_dec(v);
}

static inline Value *lumi_int(int64_t n)
{
    uint32_t size = (uint32_t)sizeof(int64_t);
    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = TAG_INT;
    v->size = size;
    v->_pad = 0;
    *(int64_t *)v->payload = n;
    return v;
}

static inline Value *lumi_str(const char *s)
{
    if (!s || s[0] == '\0')
        return (Value *)&LUMI_EMPTY_STR_VAL;

    size_t len = strlen(s) + 1;
    uint32_t size = (uint32_t)len;
    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = TAG_STR;
    v->size = size;
    v->_pad = 0;
    memcpy(v->payload, s, len);
    return v;
}

/* ── Arithmetic ──────────────────────────────────────────── */

static inline Value *int_add(Value *a, Value *b)
{
    int64_t result = *(int64_t *)a->payload + *(int64_t *)b->payload;
    rc_dec(a);
    rc_dec(b);
    return lumi_int(result);
}

static inline Value *int_sub(Value *a, Value *b)
{
    int64_t result = *(int64_t *)a->payload - *(int64_t *)b->payload;
    rc_dec(a);
    rc_dec(b);
    return lumi_int(result);
}

static inline Value *int_eq(Value *a, Value *b)
{
    int result = *(int64_t *)a->payload == *(int64_t *)b->payload;
    rc_dec(a);
    rc_dec(b);
    return lumi_bool(result);
}

/* ── Strings ─────────────────────────────────────────────── */

static inline Value *str_concat(Value *a, Value *b)
{
    const char *as = (const char *)a->payload;
    const char *bs = (const char *)b->payload;
    size_t alen = strlen(as);
    size_t blen = strlen(bs);
    uint32_t size = (uint32_t)(alen + blen + 1);

    Value *v = (Value *)malloc(sizeof(Value) + size);
    v->rc = 1;
    v->tag = TAG_STR;
    v->size = size;
    v->_pad = 0;

    memcpy(v->payload, as, alen);
    memcpy(v->payload + alen, bs, blen + 1);

    rc_dec(a);
    rc_dec(b);
    return v;
}

static inline Value *str_eq(Value *a, Value *b)
{
    int result = strcmp((const char *)a->payload, (const char *)b->payload) == 0;
    rc_dec(a);
    rc_dec(b);
    return lumi_bool(result);
}

static inline Value *str_len(Value *s)
{
    int64_t n = (int64_t)strlen((const char *)s->payload);
    rc_dec(s);
    return lumi_int(n);
}

/* Immortal singleton values */
static inline Value *lumi_int0(void) { return (Value *)&LUMI_INT0_VAL; }
static inline Value *lumi_int1(void) { return (Value *)&LUMI_INT1_VAL; }
static inline Value *lumi_empty_str(void) { return (Value *)&LUMI_EMPTY_STR_VAL; }

static inline void lumi_runtime_init(void)
{
    /* Intentionally empty: singleton values are now static and immortal. */
}

noreturn static void lumi_panic(const char *msg)
{
    fprintf(stderr, "lumi panic: %s\n", msg);
    exit(1);
}

/* ── Standard library: print helpers ────────────
 *  print() handles any Value* — tag determines the format.
 * ─────────────────────────────────────────────────────────── */

static Value *print(Value *v)
{
    if (!v)
    {
        printf("NULL");
        return lumi_unit();
    }
    switch (v->tag)
    {
    case TAG_FALSE:
        printf("False");
        rc_dec(v);
        break;
    case TAG_TRUE:
        printf("True");
        rc_dec(v);
        break;
    case TAG_UNIT:
        printf("()");
        rc_dec(v);
        break;
    case TAG_NIL:
        printf("Nil");
        rc_dec(v);
        break;
    case TAG_ZERO:
        printf("Zero");
        rc_dec(v);
        break;
    case TAG_INT:
        printf("%lld", (long long)*(int64_t *)v->payload);
        rc_dec(v);
        break;
    case TAG_STR:
        printf("%s", (const char *)v->payload);
        rc_dec(v);
        break;
    case TAG_CONS:
    {
        printf("[");
        int _first = 1;
        while (v && v->tag == TAG_CONS)
        {
            if (!_first)
                printf(", ");
            _first = 0;
            Value *head = field(v, 0);
            rc_inc(head);
            Value *tail = field(v, 1);
            rc_inc(tail);
            rc_dec(v);
            print(head);
            v = tail;
        }
        if (v)
            rc_dec(v);
        printf("]");
        break;
    }
    case TAG_SUCC:
    {
        Value *inner = field(v, 0);
        rc_inc(inner);
        rc_dec(v);
        printf("Succ(");
        print(inner);
        printf(")");
        break;
    }
    case TAG_CLOSURE:
        printf("<fn>");
        rc_dec(v);
        break;
    default:
        printf("?tag=%u", v->tag);
        rc_dec(v);
        break;
    }
    return lumi_unit();
}

static inline Value *println(Value *v)
{
    Value *x = print(v);
    printf("\n");
    return x;
}

#endif /* LUMI_RUNTIME_H */
