/* =========================================================
 * Lumi Runtime  —  generated by the Lumi compiler prototype
 * Perceus reference-counting with allocation reuse
 * ========================================================= */
#ifndef LUMI_RUNTIME_H
#define LUMI_RUNTIME_H

#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <stdnoreturn.h>

/* ── Value representation ─────────────────────────────────
 *
 *  Every heap object is a Value.  Closures set tag=TAG_CLOSURE
 *  and store a function pointer in the `fn` field.
 *  All other values leave `fn` NULL.
 *
 *  rc_dec always traverses `fields[]` regardless of tag, so
 *  closure environments are freed correctly without special cases.
 * ─────────────────────────────────────────────────────── */
struct Value;
typedef struct Value *(*LumiFn)(struct Value *env, struct Value *arg);

typedef struct Value
{
    uint32_t rc;
    uint32_t tag;
    uint32_t nfields;
    LumiFn fn; /* non-NULL only for TAG_CLOSURE */
    struct Value *fields[];
} Value;

/* ── Reuse token ─────────────────────────────────────────── */
typedef struct
{
    Value *mem;
} ReuseToken;

/* ── Constructor tags ────────────────────────────────────── */
enum
{
    TAG_FALSE = 0,
    TAG_TRUE = 1,
    TAG_NIL = 2,
    TAG_CONS = 3,
    TAG_NONE = 4,
    TAG_SOME = 5,
    TAG_SUCC = 6,
    TAG_ZERO = 7,
    TAG_CLOSURE = 0xFFFFFFFE,
};

/* ── RC primitives ───────────────────────────────────────── */

static inline void rc_inc(Value *v)
{
    if (v)
        v->rc++;
}

static inline void rc_dec(Value *v)
{
    if (!v || v->rc > 0xFFFF00)
        return; /* immortal (unit, etc.) */
    if (--v->rc == 0)
    {
        for (uint32_t i = 0; i < v->nfields; i++)
            rc_dec(v->fields[i]);
        free(v);
    }
}

/* ── Reuse primitives ────────────────────────────────────────
 *
 *  try_reuse(v): if RC==1, hand the allocation to a ReuseToken.
 *                if RC>1,  decrement and return a NULL token.
 *
 *  reuse_con / alloc_con: use or ignore the token, then
 *  initialise the header (rc=1, tag, nfields).
 * ─────────────────────────────────────────────────────────── */

static inline ReuseToken try_reuse(Value *v)
{
    if (!v)
        return (ReuseToken){NULL};
    if (v->rc == 1)
        return (ReuseToken){v};
    rc_dec(v);
    return (ReuseToken){NULL};
}

static inline Value *reuse_con(ReuseToken tok, uint32_t tag, uint32_t nfields)
{
    Value *v = tok.mem
                   ? tok.mem
                   : malloc(sizeof(Value) + nfields * sizeof(Value *));
    v->rc = 1;
    v->tag = tag;
    v->nfields = nfields;
    v->fn = NULL;
    return v;
}

static inline Value *alloc_con(uint32_t tag, uint32_t nfields)
{
    Value *v = malloc(sizeof(Value) + nfields * sizeof(Value *));
    v->rc = 1;
    v->tag = tag;
    v->nfields = nfields;
    v->fn = NULL;
    return v;
}

/* ── Closure primitives ──────────────────────────────────────
 *
 *  alloc_closure(fn, ncaptures, cap0, cap1, ...):
 *    Allocates a closure Value and stores each captured variable
 *    in fields[0..ncaptures].
 *
 *  apply(f, arg):
 *    Dispatches through f->fn.  Both f and arg are *owned* by
 *    this call (Perceus: the callee is responsible for dropping them).
 * ─────────────────────────────────────────────────────────── */

static inline Value *alloc_closure_0(LumiFn fn)
{
    Value *v = malloc(sizeof(Value));
    v->rc = 1;
    v->tag = TAG_CLOSURE;
    v->nfields = 0;
    v->fn = fn;
    return v;
}

/* Variadic helper used by generated code — each capture is a Value*. */
#include <stdarg.h>
static Value *alloc_closure(LumiFn fn, uint32_t n, ...)
{
    Value *v = malloc(sizeof(Value) + n * sizeof(Value *));
    v->rc = 1;
    v->tag = TAG_CLOSURE;
    v->nfields = n;
    v->fn = fn;
    va_list ap;
    va_start(ap, n);
    for (uint32_t i = 0; i < n; i++)
        v->fields[i] = va_arg(ap, Value *);
    va_end(ap);
    return v;
}

static inline Value *apply(Value *f, Value *arg)
{
    /* f is owned; the callee will rc_dec(_env) to release it. */
    return f->fn(f, arg);
}

/* ── Primitive value constructors ────────────────────────── */

static Value LUMI_UNIT_VAL = {.rc = 0xFFFFFFFF, .tag = 0, .nfields = 0, .fn = NULL};

static inline Value *lumi_unit(void) { return &LUMI_UNIT_VAL; }
static inline Value *lumi_bool(int b) { return alloc_con(b ? TAG_TRUE : TAG_FALSE, 0); }
static inline int lumi_is_true(Value *v) { return v && v->tag != 0; }
static inline uint32_t tag_of(Value *v) { return v ? v->tag : 0; }
static inline Value *field(Value *v, uint32_t i) { return v->fields[i]; }

/* Pins a value as an immortal global binding.  Immortal values are never
 * freed by rc_dec, so a recursive closure can apply() the global safely
 * without worrying about its RC reaching zero mid-recursion.
 * Call lumi_release_global() when done to reclaim the allocation. */
static inline Value *lumi_global(Value *v)
{
    v->rc = 0xFFFFFFFF;
    return v;
}
static inline void lumi_release_global(Value *v)
{
    v->rc = 1;
    rc_dec(v);
}

static inline Value *lumi_int(int64_t n)
{
    /* Boxes an integer.  A production compiler would use tagged pointers
     * for small integers to avoid this allocation. */
    Value *v = malloc(sizeof(Value) + sizeof(int64_t));
    v->rc = 1;
    v->tag = 0;
    v->nfields = 0;
    v->fn = NULL;
    *(int64_t *)(v + 1) = n;
    return v;
}

noreturn static void lumi_panic(const char *msg)
{
    fprintf(stderr, "lumi panic: %s\n", msg);
    exit(1);
}

#endif /* LUMI_RUNTIME_H */
